# == Schema Information
#
# Table name: follows
#
#  id          :integer          not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  followed_id :integer          not null
#  follower_id :integer          not null
#
# Indexes
#
#  index_follows_on_followed_id  (followed_id)
#  index_follows_on_follower_id  (follower_id)
#
# Foreign Keys
#
#  followed_id  (followed_id => followeds.id)
#  follower_id  (follower_id => followers.id)
#
class Follow < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # Variabels .................................................................
  # relationships .............................................................
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  # validations ...............................................................
  validates :follower_id, uniqueness: { scope: :followed_id } # to avoid muliple data
  validates :followed_id, uniqueness: { scope: :follower_id } # to avoid muliple data
  # callbacks .................................................................
  # scopes ....................................................................
  # uploaders .................................................................
  # additional config (i.e. accepts_nested_attributes_for etc...) .............
  # auditeds ..................................................................
  # enums .....................................................................
  # delegate ..................................................................
end
